/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormSubmitEvent, OntologyOption } from "./components/overrep-form/overrep-form";
export { FormSubmitEvent, OntologyOption } from "./components/overrep-form/overrep-form";
export namespace Components {
    interface OverrepForm {
        /**
          * @default []
         */
        "exampleGenes": string[];
        /**
          * @default 'Examples'
         */
        "examplesLabel": string;
        /**
          * @default 'Your Gene IDs'
         */
        "geneIdsLabel": string;
        /**
          * @default 'can use UniProt ID/AC, Gene Name, Gene Symbols'
         */
        "hint": string;
        /**
          * @default 'Ontology'
         */
        "ontologyLabel": string;
        /**
          * @default []
         */
        "ontologyOptions": OntologyOption[];
        /**
          * @default true
         */
        "showHint": boolean;
        /**
          * @default 'HUMAN'
         */
        "species": string;
        /**
          * @default 'Launch'
         */
        "submitLabel": string;
        /**
          * @default '/api/overrep'
         */
        "submitUrl": string;
        /**
          * @default 'FISHER'
         */
        "testType": string;
        /**
          * @default 3
         */
        "textareaRows": number;
    }
    interface PangoDropdown {
    }
    interface PangoGene {
        "geneId": string;
    }
    interface PangoToolbar {
        /**
          * @default 'Human Functionome'
         */
        "headerSubTitle": string;
        /**
          * @default 'PAN-GO'
         */
        "headerTitle": string;
        /**
          * @default '/'
         */
        "pangoHome": string;
    }
}
export interface OverrepFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOverrepFormElement;
}
export interface PangoDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPangoDropdownElement;
}
declare global {
    interface HTMLOverrepFormElementEventMap {
        "overrepSubmit": FormSubmitEvent;
    }
    interface HTMLOverrepFormElement extends Components.OverrepForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOverrepFormElementEventMap>(type: K, listener: (this: HTMLOverrepFormElement, ev: OverrepFormCustomEvent<HTMLOverrepFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOverrepFormElementEventMap>(type: K, listener: (this: HTMLOverrepFormElement, ev: OverrepFormCustomEvent<HTMLOverrepFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOverrepFormElement: {
        prototype: HTMLOverrepFormElement;
        new (): HTMLOverrepFormElement;
    };
    interface HTMLPangoDropdownElementEventMap {
        "dropdownToggle": boolean;
    }
    interface HTMLPangoDropdownElement extends Components.PangoDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPangoDropdownElementEventMap>(type: K, listener: (this: HTMLPangoDropdownElement, ev: PangoDropdownCustomEvent<HTMLPangoDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPangoDropdownElementEventMap>(type: K, listener: (this: HTMLPangoDropdownElement, ev: PangoDropdownCustomEvent<HTMLPangoDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPangoDropdownElement: {
        prototype: HTMLPangoDropdownElement;
        new (): HTMLPangoDropdownElement;
    };
    interface HTMLPangoGeneElement extends Components.PangoGene, HTMLStencilElement {
    }
    var HTMLPangoGeneElement: {
        prototype: HTMLPangoGeneElement;
        new (): HTMLPangoGeneElement;
    };
    interface HTMLPangoToolbarElement extends Components.PangoToolbar, HTMLStencilElement {
    }
    var HTMLPangoToolbarElement: {
        prototype: HTMLPangoToolbarElement;
        new (): HTMLPangoToolbarElement;
    };
    interface HTMLElementTagNameMap {
        "overrep-form": HTMLOverrepFormElement;
        "pango-dropdown": HTMLPangoDropdownElement;
        "pango-gene": HTMLPangoGeneElement;
        "pango-toolbar": HTMLPangoToolbarElement;
    }
}
declare namespace LocalJSX {
    interface OverrepForm {
        /**
          * @default []
         */
        "exampleGenes"?: string[];
        /**
          * @default 'Examples'
         */
        "examplesLabel"?: string;
        /**
          * @default 'Your Gene IDs'
         */
        "geneIdsLabel"?: string;
        /**
          * @default 'can use UniProt ID/AC, Gene Name, Gene Symbols'
         */
        "hint"?: string;
        "onOverrepSubmit"?: (event: OverrepFormCustomEvent<FormSubmitEvent>) => void;
        /**
          * @default 'Ontology'
         */
        "ontologyLabel"?: string;
        /**
          * @default []
         */
        "ontologyOptions"?: OntologyOption[];
        /**
          * @default true
         */
        "showHint"?: boolean;
        /**
          * @default 'HUMAN'
         */
        "species"?: string;
        /**
          * @default 'Launch'
         */
        "submitLabel"?: string;
        /**
          * @default '/api/overrep'
         */
        "submitUrl"?: string;
        /**
          * @default 'FISHER'
         */
        "testType"?: string;
        /**
          * @default 3
         */
        "textareaRows"?: number;
    }
    interface PangoDropdown {
        "onDropdownToggle"?: (event: PangoDropdownCustomEvent<boolean>) => void;
    }
    interface PangoGene {
        "geneId": string;
    }
    interface PangoToolbar {
        /**
          * @default 'Human Functionome'
         */
        "headerSubTitle"?: string;
        /**
          * @default 'PAN-GO'
         */
        "headerTitle"?: string;
        /**
          * @default '/'
         */
        "pangoHome"?: string;
    }
    interface IntrinsicElements {
        "overrep-form": OverrepForm;
        "pango-dropdown": PangoDropdown;
        "pango-gene": PangoGene;
        "pango-toolbar": PangoToolbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "overrep-form": LocalJSX.OverrepForm & JSXBase.HTMLAttributes<HTMLOverrepFormElement>;
            "pango-dropdown": LocalJSX.PangoDropdown & JSXBase.HTMLAttributes<HTMLPangoDropdownElement>;
            "pango-gene": LocalJSX.PangoGene & JSXBase.HTMLAttributes<HTMLPangoGeneElement>;
            "pango-toolbar": LocalJSX.PangoToolbar & JSXBase.HTMLAttributes<HTMLPangoToolbarElement>;
        }
    }
}
